package com.gs.store.dto;

public class SysCustDTO {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_cust.cust_id
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	private Long custId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_cust.cust_name
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	private String custName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_cust.cust_plate_name
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	private String custPlateName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_cust.cust_pid
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	private Long custPid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_cust.address
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	private String address;
	public Long getCustId() {
		return custId;
	}
	public void setCustId(Long custId) {
		this.custId = custId;
	}
	public String getCustName() {
		return custName;
	}
	public void setCustName(String custName) {
		this.custName = custName;
	}
	public String getCustPlateName() {
		return custPlateName;
	}
	public void setCustPlateName(String custPlateName) {
		this.custPlateName = custPlateName;
	}
	public Long getCustPid() {
		return custPid;
	}
	public void setCustPid(Long custPid) {
		this.custPid = custPid;
	}
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
}
