package com.gs.sys.model;

import java.util.Date;

public class SysCust {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_cust.cust_id
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	private Long custId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_cust.cust_name
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	private String custName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_cust.cust_plate_name
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	private String custPlateName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_cust.cust_pid
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	private Long custPid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_cust.address
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_cust.created_code
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	private String createdCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_cust.created_dt
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	private Date createdDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_cust.updated_code
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	private String updatedCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_cust.updated_dt
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	private Date updatedDt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_cust.cust_id
	 * @return  the value of sys_cust.cust_id
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	public Long getCustId() {
		return custId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_cust.cust_id
	 * @param custId  the value for sys_cust.cust_id
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	public void setCustId(Long custId) {
		this.custId = custId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_cust.cust_name
	 * @return  the value of sys_cust.cust_name
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	public String getCustName() {
		return custName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_cust.cust_name
	 * @param custName  the value for sys_cust.cust_name
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	public void setCustName(String custName) {
		this.custName = custName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_cust.cust_plate_name
	 * @return  the value of sys_cust.cust_plate_name
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	public String getCustPlateName() {
		return custPlateName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_cust.cust_plate_name
	 * @param custPlateName  the value for sys_cust.cust_plate_name
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	public void setCustPlateName(String custPlateName) {
		this.custPlateName = custPlateName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_cust.cust_pid
	 * @return  the value of sys_cust.cust_pid
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	public Long getCustPid() {
		return custPid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_cust.cust_pid
	 * @param custPid  the value for sys_cust.cust_pid
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	public void setCustPid(Long custPid) {
		this.custPid = custPid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_cust.address
	 * @return  the value of sys_cust.address
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_cust.address
	 * @param address  the value for sys_cust.address
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_cust.created_code
	 * @return  the value of sys_cust.created_code
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	public String getCreatedCode() {
		return createdCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_cust.created_code
	 * @param createdCode  the value for sys_cust.created_code
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	public void setCreatedCode(String createdCode) {
		this.createdCode = createdCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_cust.created_dt
	 * @return  the value of sys_cust.created_dt
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	public Date getCreatedDt() {
		return createdDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_cust.created_dt
	 * @param createdDt  the value for sys_cust.created_dt
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	public void setCreatedDt(Date createdDt) {
		this.createdDt = createdDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_cust.updated_code
	 * @return  the value of sys_cust.updated_code
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	public String getUpdatedCode() {
		return updatedCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_cust.updated_code
	 * @param updatedCode  the value for sys_cust.updated_code
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	public void setUpdatedCode(String updatedCode) {
		this.updatedCode = updatedCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_cust.updated_dt
	 * @return  the value of sys_cust.updated_dt
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	public Date getUpdatedDt() {
		return updatedDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_cust.updated_dt
	 * @param updatedDt  the value for sys_cust.updated_dt
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	public void setUpdatedDt(Date updatedDt) {
		this.updatedDt = updatedDt;
	}
}