package com.gs.sys.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysCustExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_cust
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_cust
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_cust
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_cust
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	public SysCustExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_cust
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_cust
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_cust
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_cust
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_cust
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_cust
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_cust
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_cust
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_cust
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_cust
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sys_cust
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCustIdIsNull() {
			addCriterion("cust_id is null");
			return (Criteria) this;
		}

		public Criteria andCustIdIsNotNull() {
			addCriterion("cust_id is not null");
			return (Criteria) this;
		}

		public Criteria andCustIdEqualTo(Long value) {
			addCriterion("cust_id =", value, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdNotEqualTo(Long value) {
			addCriterion("cust_id <>", value, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdGreaterThan(Long value) {
			addCriterion("cust_id >", value, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdGreaterThanOrEqualTo(Long value) {
			addCriterion("cust_id >=", value, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdLessThan(Long value) {
			addCriterion("cust_id <", value, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdLessThanOrEqualTo(Long value) {
			addCriterion("cust_id <=", value, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdIn(List<Long> values) {
			addCriterion("cust_id in", values, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdNotIn(List<Long> values) {
			addCriterion("cust_id not in", values, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdBetween(Long value1, Long value2) {
			addCriterion("cust_id between", value1, value2, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdNotBetween(Long value1, Long value2) {
			addCriterion("cust_id not between", value1, value2, "custId");
			return (Criteria) this;
		}

		public Criteria andCustNameIsNull() {
			addCriterion("cust_name is null");
			return (Criteria) this;
		}

		public Criteria andCustNameIsNotNull() {
			addCriterion("cust_name is not null");
			return (Criteria) this;
		}

		public Criteria andCustNameEqualTo(String value) {
			addCriterion("cust_name =", value, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameNotEqualTo(String value) {
			addCriterion("cust_name <>", value, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameGreaterThan(String value) {
			addCriterion("cust_name >", value, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameGreaterThanOrEqualTo(String value) {
			addCriterion("cust_name >=", value, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameLessThan(String value) {
			addCriterion("cust_name <", value, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameLessThanOrEqualTo(String value) {
			addCriterion("cust_name <=", value, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameLike(String value) {
			addCriterion("cust_name like", value, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameNotLike(String value) {
			addCriterion("cust_name not like", value, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameIn(List<String> values) {
			addCriterion("cust_name in", values, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameNotIn(List<String> values) {
			addCriterion("cust_name not in", values, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameBetween(String value1, String value2) {
			addCriterion("cust_name between", value1, value2, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameNotBetween(String value1, String value2) {
			addCriterion("cust_name not between", value1, value2, "custName");
			return (Criteria) this;
		}

		public Criteria andCustPlateNameIsNull() {
			addCriterion("cust_plate_name is null");
			return (Criteria) this;
		}

		public Criteria andCustPlateNameIsNotNull() {
			addCriterion("cust_plate_name is not null");
			return (Criteria) this;
		}

		public Criteria andCustPlateNameEqualTo(String value) {
			addCriterion("cust_plate_name =", value, "custPlateName");
			return (Criteria) this;
		}

		public Criteria andCustPlateNameNotEqualTo(String value) {
			addCriterion("cust_plate_name <>", value, "custPlateName");
			return (Criteria) this;
		}

		public Criteria andCustPlateNameGreaterThan(String value) {
			addCriterion("cust_plate_name >", value, "custPlateName");
			return (Criteria) this;
		}

		public Criteria andCustPlateNameGreaterThanOrEqualTo(String value) {
			addCriterion("cust_plate_name >=", value, "custPlateName");
			return (Criteria) this;
		}

		public Criteria andCustPlateNameLessThan(String value) {
			addCriterion("cust_plate_name <", value, "custPlateName");
			return (Criteria) this;
		}

		public Criteria andCustPlateNameLessThanOrEqualTo(String value) {
			addCriterion("cust_plate_name <=", value, "custPlateName");
			return (Criteria) this;
		}

		public Criteria andCustPlateNameLike(String value) {
			addCriterion("cust_plate_name like", value, "custPlateName");
			return (Criteria) this;
		}

		public Criteria andCustPlateNameNotLike(String value) {
			addCriterion("cust_plate_name not like", value, "custPlateName");
			return (Criteria) this;
		}

		public Criteria andCustPlateNameIn(List<String> values) {
			addCriterion("cust_plate_name in", values, "custPlateName");
			return (Criteria) this;
		}

		public Criteria andCustPlateNameNotIn(List<String> values) {
			addCriterion("cust_plate_name not in", values, "custPlateName");
			return (Criteria) this;
		}

		public Criteria andCustPlateNameBetween(String value1, String value2) {
			addCriterion("cust_plate_name between", value1, value2,
					"custPlateName");
			return (Criteria) this;
		}

		public Criteria andCustPlateNameNotBetween(String value1, String value2) {
			addCriterion("cust_plate_name not between", value1, value2,
					"custPlateName");
			return (Criteria) this;
		}

		public Criteria andCustPidIsNull() {
			addCriterion("cust_pid is null");
			return (Criteria) this;
		}

		public Criteria andCustPidIsNotNull() {
			addCriterion("cust_pid is not null");
			return (Criteria) this;
		}

		public Criteria andCustPidEqualTo(Long value) {
			addCriterion("cust_pid =", value, "custPid");
			return (Criteria) this;
		}

		public Criteria andCustPidNotEqualTo(Long value) {
			addCriterion("cust_pid <>", value, "custPid");
			return (Criteria) this;
		}

		public Criteria andCustPidGreaterThan(Long value) {
			addCriterion("cust_pid >", value, "custPid");
			return (Criteria) this;
		}

		public Criteria andCustPidGreaterThanOrEqualTo(Long value) {
			addCriterion("cust_pid >=", value, "custPid");
			return (Criteria) this;
		}

		public Criteria andCustPidLessThan(Long value) {
			addCriterion("cust_pid <", value, "custPid");
			return (Criteria) this;
		}

		public Criteria andCustPidLessThanOrEqualTo(Long value) {
			addCriterion("cust_pid <=", value, "custPid");
			return (Criteria) this;
		}

		public Criteria andCustPidIn(List<Long> values) {
			addCriterion("cust_pid in", values, "custPid");
			return (Criteria) this;
		}

		public Criteria andCustPidNotIn(List<Long> values) {
			addCriterion("cust_pid not in", values, "custPid");
			return (Criteria) this;
		}

		public Criteria andCustPidBetween(Long value1, Long value2) {
			addCriterion("cust_pid between", value1, value2, "custPid");
			return (Criteria) this;
		}

		public Criteria andCustPidNotBetween(Long value1, Long value2) {
			addCriterion("cust_pid not between", value1, value2, "custPid");
			return (Criteria) this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("address is null");
			return (Criteria) this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("address is not null");
			return (Criteria) this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("address =", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("address <>", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("address >", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("address >=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("address <", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("address <=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("address like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("address not like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("address in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("address not in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("address between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("address not between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andCreatedCodeIsNull() {
			addCriterion("created_code is null");
			return (Criteria) this;
		}

		public Criteria andCreatedCodeIsNotNull() {
			addCriterion("created_code is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedCodeEqualTo(String value) {
			addCriterion("created_code =", value, "createdCode");
			return (Criteria) this;
		}

		public Criteria andCreatedCodeNotEqualTo(String value) {
			addCriterion("created_code <>", value, "createdCode");
			return (Criteria) this;
		}

		public Criteria andCreatedCodeGreaterThan(String value) {
			addCriterion("created_code >", value, "createdCode");
			return (Criteria) this;
		}

		public Criteria andCreatedCodeGreaterThanOrEqualTo(String value) {
			addCriterion("created_code >=", value, "createdCode");
			return (Criteria) this;
		}

		public Criteria andCreatedCodeLessThan(String value) {
			addCriterion("created_code <", value, "createdCode");
			return (Criteria) this;
		}

		public Criteria andCreatedCodeLessThanOrEqualTo(String value) {
			addCriterion("created_code <=", value, "createdCode");
			return (Criteria) this;
		}

		public Criteria andCreatedCodeLike(String value) {
			addCriterion("created_code like", value, "createdCode");
			return (Criteria) this;
		}

		public Criteria andCreatedCodeNotLike(String value) {
			addCriterion("created_code not like", value, "createdCode");
			return (Criteria) this;
		}

		public Criteria andCreatedCodeIn(List<String> values) {
			addCriterion("created_code in", values, "createdCode");
			return (Criteria) this;
		}

		public Criteria andCreatedCodeNotIn(List<String> values) {
			addCriterion("created_code not in", values, "createdCode");
			return (Criteria) this;
		}

		public Criteria andCreatedCodeBetween(String value1, String value2) {
			addCriterion("created_code between", value1, value2, "createdCode");
			return (Criteria) this;
		}

		public Criteria andCreatedCodeNotBetween(String value1, String value2) {
			addCriterion("created_code not between", value1, value2,
					"createdCode");
			return (Criteria) this;
		}

		public Criteria andCreatedDtIsNull() {
			addCriterion("created_dt is null");
			return (Criteria) this;
		}

		public Criteria andCreatedDtIsNotNull() {
			addCriterion("created_dt is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedDtEqualTo(Date value) {
			addCriterion("created_dt =", value, "createdDt");
			return (Criteria) this;
		}

		public Criteria andCreatedDtNotEqualTo(Date value) {
			addCriterion("created_dt <>", value, "createdDt");
			return (Criteria) this;
		}

		public Criteria andCreatedDtGreaterThan(Date value) {
			addCriterion("created_dt >", value, "createdDt");
			return (Criteria) this;
		}

		public Criteria andCreatedDtGreaterThanOrEqualTo(Date value) {
			addCriterion("created_dt >=", value, "createdDt");
			return (Criteria) this;
		}

		public Criteria andCreatedDtLessThan(Date value) {
			addCriterion("created_dt <", value, "createdDt");
			return (Criteria) this;
		}

		public Criteria andCreatedDtLessThanOrEqualTo(Date value) {
			addCriterion("created_dt <=", value, "createdDt");
			return (Criteria) this;
		}

		public Criteria andCreatedDtIn(List<Date> values) {
			addCriterion("created_dt in", values, "createdDt");
			return (Criteria) this;
		}

		public Criteria andCreatedDtNotIn(List<Date> values) {
			addCriterion("created_dt not in", values, "createdDt");
			return (Criteria) this;
		}

		public Criteria andCreatedDtBetween(Date value1, Date value2) {
			addCriterion("created_dt between", value1, value2, "createdDt");
			return (Criteria) this;
		}

		public Criteria andCreatedDtNotBetween(Date value1, Date value2) {
			addCriterion("created_dt not between", value1, value2, "createdDt");
			return (Criteria) this;
		}

		public Criteria andUpdatedCodeIsNull() {
			addCriterion("updated_code is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedCodeIsNotNull() {
			addCriterion("updated_code is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedCodeEqualTo(String value) {
			addCriterion("updated_code =", value, "updatedCode");
			return (Criteria) this;
		}

		public Criteria andUpdatedCodeNotEqualTo(String value) {
			addCriterion("updated_code <>", value, "updatedCode");
			return (Criteria) this;
		}

		public Criteria andUpdatedCodeGreaterThan(String value) {
			addCriterion("updated_code >", value, "updatedCode");
			return (Criteria) this;
		}

		public Criteria andUpdatedCodeGreaterThanOrEqualTo(String value) {
			addCriterion("updated_code >=", value, "updatedCode");
			return (Criteria) this;
		}

		public Criteria andUpdatedCodeLessThan(String value) {
			addCriterion("updated_code <", value, "updatedCode");
			return (Criteria) this;
		}

		public Criteria andUpdatedCodeLessThanOrEqualTo(String value) {
			addCriterion("updated_code <=", value, "updatedCode");
			return (Criteria) this;
		}

		public Criteria andUpdatedCodeLike(String value) {
			addCriterion("updated_code like", value, "updatedCode");
			return (Criteria) this;
		}

		public Criteria andUpdatedCodeNotLike(String value) {
			addCriterion("updated_code not like", value, "updatedCode");
			return (Criteria) this;
		}

		public Criteria andUpdatedCodeIn(List<String> values) {
			addCriterion("updated_code in", values, "updatedCode");
			return (Criteria) this;
		}

		public Criteria andUpdatedCodeNotIn(List<String> values) {
			addCriterion("updated_code not in", values, "updatedCode");
			return (Criteria) this;
		}

		public Criteria andUpdatedCodeBetween(String value1, String value2) {
			addCriterion("updated_code between", value1, value2, "updatedCode");
			return (Criteria) this;
		}

		public Criteria andUpdatedCodeNotBetween(String value1, String value2) {
			addCriterion("updated_code not between", value1, value2,
					"updatedCode");
			return (Criteria) this;
		}

		public Criteria andUpdatedDtIsNull() {
			addCriterion("updated_dt is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedDtIsNotNull() {
			addCriterion("updated_dt is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedDtEqualTo(Date value) {
			addCriterion("updated_dt =", value, "updatedDt");
			return (Criteria) this;
		}

		public Criteria andUpdatedDtNotEqualTo(Date value) {
			addCriterion("updated_dt <>", value, "updatedDt");
			return (Criteria) this;
		}

		public Criteria andUpdatedDtGreaterThan(Date value) {
			addCriterion("updated_dt >", value, "updatedDt");
			return (Criteria) this;
		}

		public Criteria andUpdatedDtGreaterThanOrEqualTo(Date value) {
			addCriterion("updated_dt >=", value, "updatedDt");
			return (Criteria) this;
		}

		public Criteria andUpdatedDtLessThan(Date value) {
			addCriterion("updated_dt <", value, "updatedDt");
			return (Criteria) this;
		}

		public Criteria andUpdatedDtLessThanOrEqualTo(Date value) {
			addCriterion("updated_dt <=", value, "updatedDt");
			return (Criteria) this;
		}

		public Criteria andUpdatedDtIn(List<Date> values) {
			addCriterion("updated_dt in", values, "updatedDt");
			return (Criteria) this;
		}

		public Criteria andUpdatedDtNotIn(List<Date> values) {
			addCriterion("updated_dt not in", values, "updatedDt");
			return (Criteria) this;
		}

		public Criteria andUpdatedDtBetween(Date value1, Date value2) {
			addCriterion("updated_dt between", value1, value2, "updatedDt");
			return (Criteria) this;
		}

		public Criteria andUpdatedDtNotBetween(Date value1, Date value2) {
			addCriterion("updated_dt not between", value1, value2, "updatedDt");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sys_cust
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_cust
     *
     * @mbggenerated do_not_delete_during_merge Sun Dec 03 20:19:51 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}