package com.gs.sys.model;

public class SysMenu {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_menu.menu_id
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	private Integer menuId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_menu.text
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	private String text;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_menu.menu_desc
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	private String menuDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_menu.menu_pid
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	private Integer menuPid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_menu.order_seq
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	private Integer orderSeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_menu.action
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	private String action;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_menu.leaf
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	private Integer leaf;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_menu.menu_id
	 * @return  the value of sys_menu.menu_id
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	public Integer getMenuId() {
		return menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_menu.menu_id
	 * @param menuId  the value for sys_menu.menu_id
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_menu.text
	 * @return  the value of sys_menu.text
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	public String getText() {
		return text;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_menu.text
	 * @param text  the value for sys_menu.text
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	public void setText(String text) {
		this.text = text;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_menu.menu_desc
	 * @return  the value of sys_menu.menu_desc
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	public String getMenuDesc() {
		return menuDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_menu.menu_desc
	 * @param menuDesc  the value for sys_menu.menu_desc
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	public void setMenuDesc(String menuDesc) {
		this.menuDesc = menuDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_menu.menu_pid
	 * @return  the value of sys_menu.menu_pid
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	public Integer getMenuPid() {
		return menuPid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_menu.menu_pid
	 * @param menuPid  the value for sys_menu.menu_pid
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	public void setMenuPid(Integer menuPid) {
		this.menuPid = menuPid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_menu.order_seq
	 * @return  the value of sys_menu.order_seq
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	public Integer getOrderSeq() {
		return orderSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_menu.order_seq
	 * @param orderSeq  the value for sys_menu.order_seq
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	public void setOrderSeq(Integer orderSeq) {
		this.orderSeq = orderSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_menu.action
	 * @return  the value of sys_menu.action
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	public String getAction() {
		return action;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_menu.action
	 * @param action  the value for sys_menu.action
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	public void setAction(String action) {
		this.action = action;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_menu.leaf
	 * @return  the value of sys_menu.leaf
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	public Integer getLeaf() {
		return leaf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_menu.leaf
	 * @param leaf  the value for sys_menu.leaf
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	public void setLeaf(Integer leaf) {
		this.leaf = leaf;
	}
}