package com.gs.sys.model;

import java.util.ArrayList;
import java.util.List;

public class SysMenuExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_menu
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_menu
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_menu
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	public SysMenuExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sys_menu
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andMenuIdIsNull() {
			addCriterion("menu_id is null");
			return (Criteria) this;
		}

		public Criteria andMenuIdIsNotNull() {
			addCriterion("menu_id is not null");
			return (Criteria) this;
		}

		public Criteria andMenuIdEqualTo(Integer value) {
			addCriterion("menu_id =", value, "menuId");
			return (Criteria) this;
		}

		public Criteria andMenuIdNotEqualTo(Integer value) {
			addCriterion("menu_id <>", value, "menuId");
			return (Criteria) this;
		}

		public Criteria andMenuIdGreaterThan(Integer value) {
			addCriterion("menu_id >", value, "menuId");
			return (Criteria) this;
		}

		public Criteria andMenuIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("menu_id >=", value, "menuId");
			return (Criteria) this;
		}

		public Criteria andMenuIdLessThan(Integer value) {
			addCriterion("menu_id <", value, "menuId");
			return (Criteria) this;
		}

		public Criteria andMenuIdLessThanOrEqualTo(Integer value) {
			addCriterion("menu_id <=", value, "menuId");
			return (Criteria) this;
		}

		public Criteria andMenuIdIn(List<Integer> values) {
			addCriterion("menu_id in", values, "menuId");
			return (Criteria) this;
		}

		public Criteria andMenuIdNotIn(List<Integer> values) {
			addCriterion("menu_id not in", values, "menuId");
			return (Criteria) this;
		}

		public Criteria andMenuIdBetween(Integer value1, Integer value2) {
			addCriterion("menu_id between", value1, value2, "menuId");
			return (Criteria) this;
		}

		public Criteria andMenuIdNotBetween(Integer value1, Integer value2) {
			addCriterion("menu_id not between", value1, value2, "menuId");
			return (Criteria) this;
		}

		public Criteria andTextIsNull() {
			addCriterion("text is null");
			return (Criteria) this;
		}

		public Criteria andTextIsNotNull() {
			addCriterion("text is not null");
			return (Criteria) this;
		}

		public Criteria andTextEqualTo(String value) {
			addCriterion("text =", value, "text");
			return (Criteria) this;
		}

		public Criteria andTextNotEqualTo(String value) {
			addCriterion("text <>", value, "text");
			return (Criteria) this;
		}

		public Criteria andTextGreaterThan(String value) {
			addCriterion("text >", value, "text");
			return (Criteria) this;
		}

		public Criteria andTextGreaterThanOrEqualTo(String value) {
			addCriterion("text >=", value, "text");
			return (Criteria) this;
		}

		public Criteria andTextLessThan(String value) {
			addCriterion("text <", value, "text");
			return (Criteria) this;
		}

		public Criteria andTextLessThanOrEqualTo(String value) {
			addCriterion("text <=", value, "text");
			return (Criteria) this;
		}

		public Criteria andTextLike(String value) {
			addCriterion("text like", value, "text");
			return (Criteria) this;
		}

		public Criteria andTextNotLike(String value) {
			addCriterion("text not like", value, "text");
			return (Criteria) this;
		}

		public Criteria andTextIn(List<String> values) {
			addCriterion("text in", values, "text");
			return (Criteria) this;
		}

		public Criteria andTextNotIn(List<String> values) {
			addCriterion("text not in", values, "text");
			return (Criteria) this;
		}

		public Criteria andTextBetween(String value1, String value2) {
			addCriterion("text between", value1, value2, "text");
			return (Criteria) this;
		}

		public Criteria andTextNotBetween(String value1, String value2) {
			addCriterion("text not between", value1, value2, "text");
			return (Criteria) this;
		}

		public Criteria andMenuDescIsNull() {
			addCriterion("menu_desc is null");
			return (Criteria) this;
		}

		public Criteria andMenuDescIsNotNull() {
			addCriterion("menu_desc is not null");
			return (Criteria) this;
		}

		public Criteria andMenuDescEqualTo(String value) {
			addCriterion("menu_desc =", value, "menuDesc");
			return (Criteria) this;
		}

		public Criteria andMenuDescNotEqualTo(String value) {
			addCriterion("menu_desc <>", value, "menuDesc");
			return (Criteria) this;
		}

		public Criteria andMenuDescGreaterThan(String value) {
			addCriterion("menu_desc >", value, "menuDesc");
			return (Criteria) this;
		}

		public Criteria andMenuDescGreaterThanOrEqualTo(String value) {
			addCriterion("menu_desc >=", value, "menuDesc");
			return (Criteria) this;
		}

		public Criteria andMenuDescLessThan(String value) {
			addCriterion("menu_desc <", value, "menuDesc");
			return (Criteria) this;
		}

		public Criteria andMenuDescLessThanOrEqualTo(String value) {
			addCriterion("menu_desc <=", value, "menuDesc");
			return (Criteria) this;
		}

		public Criteria andMenuDescLike(String value) {
			addCriterion("menu_desc like", value, "menuDesc");
			return (Criteria) this;
		}

		public Criteria andMenuDescNotLike(String value) {
			addCriterion("menu_desc not like", value, "menuDesc");
			return (Criteria) this;
		}

		public Criteria andMenuDescIn(List<String> values) {
			addCriterion("menu_desc in", values, "menuDesc");
			return (Criteria) this;
		}

		public Criteria andMenuDescNotIn(List<String> values) {
			addCriterion("menu_desc not in", values, "menuDesc");
			return (Criteria) this;
		}

		public Criteria andMenuDescBetween(String value1, String value2) {
			addCriterion("menu_desc between", value1, value2, "menuDesc");
			return (Criteria) this;
		}

		public Criteria andMenuDescNotBetween(String value1, String value2) {
			addCriterion("menu_desc not between", value1, value2, "menuDesc");
			return (Criteria) this;
		}

		public Criteria andMenuPidIsNull() {
			addCriterion("menu_pid is null");
			return (Criteria) this;
		}

		public Criteria andMenuPidIsNotNull() {
			addCriterion("menu_pid is not null");
			return (Criteria) this;
		}

		public Criteria andMenuPidEqualTo(Integer value) {
			addCriterion("menu_pid =", value, "menuPid");
			return (Criteria) this;
		}

		public Criteria andMenuPidNotEqualTo(Integer value) {
			addCriterion("menu_pid <>", value, "menuPid");
			return (Criteria) this;
		}

		public Criteria andMenuPidGreaterThan(Integer value) {
			addCriterion("menu_pid >", value, "menuPid");
			return (Criteria) this;
		}

		public Criteria andMenuPidGreaterThanOrEqualTo(Integer value) {
			addCriterion("menu_pid >=", value, "menuPid");
			return (Criteria) this;
		}

		public Criteria andMenuPidLessThan(Integer value) {
			addCriterion("menu_pid <", value, "menuPid");
			return (Criteria) this;
		}

		public Criteria andMenuPidLessThanOrEqualTo(Integer value) {
			addCriterion("menu_pid <=", value, "menuPid");
			return (Criteria) this;
		}

		public Criteria andMenuPidIn(List<Integer> values) {
			addCriterion("menu_pid in", values, "menuPid");
			return (Criteria) this;
		}

		public Criteria andMenuPidNotIn(List<Integer> values) {
			addCriterion("menu_pid not in", values, "menuPid");
			return (Criteria) this;
		}

		public Criteria andMenuPidBetween(Integer value1, Integer value2) {
			addCriterion("menu_pid between", value1, value2, "menuPid");
			return (Criteria) this;
		}

		public Criteria andMenuPidNotBetween(Integer value1, Integer value2) {
			addCriterion("menu_pid not between", value1, value2, "menuPid");
			return (Criteria) this;
		}

		public Criteria andOrderSeqIsNull() {
			addCriterion("order_seq is null");
			return (Criteria) this;
		}

		public Criteria andOrderSeqIsNotNull() {
			addCriterion("order_seq is not null");
			return (Criteria) this;
		}

		public Criteria andOrderSeqEqualTo(Integer value) {
			addCriterion("order_seq =", value, "orderSeq");
			return (Criteria) this;
		}

		public Criteria andOrderSeqNotEqualTo(Integer value) {
			addCriterion("order_seq <>", value, "orderSeq");
			return (Criteria) this;
		}

		public Criteria andOrderSeqGreaterThan(Integer value) {
			addCriterion("order_seq >", value, "orderSeq");
			return (Criteria) this;
		}

		public Criteria andOrderSeqGreaterThanOrEqualTo(Integer value) {
			addCriterion("order_seq >=", value, "orderSeq");
			return (Criteria) this;
		}

		public Criteria andOrderSeqLessThan(Integer value) {
			addCriterion("order_seq <", value, "orderSeq");
			return (Criteria) this;
		}

		public Criteria andOrderSeqLessThanOrEqualTo(Integer value) {
			addCriterion("order_seq <=", value, "orderSeq");
			return (Criteria) this;
		}

		public Criteria andOrderSeqIn(List<Integer> values) {
			addCriterion("order_seq in", values, "orderSeq");
			return (Criteria) this;
		}

		public Criteria andOrderSeqNotIn(List<Integer> values) {
			addCriterion("order_seq not in", values, "orderSeq");
			return (Criteria) this;
		}

		public Criteria andOrderSeqBetween(Integer value1, Integer value2) {
			addCriterion("order_seq between", value1, value2, "orderSeq");
			return (Criteria) this;
		}

		public Criteria andOrderSeqNotBetween(Integer value1, Integer value2) {
			addCriterion("order_seq not between", value1, value2, "orderSeq");
			return (Criteria) this;
		}

		public Criteria andActionIsNull() {
			addCriterion("action is null");
			return (Criteria) this;
		}

		public Criteria andActionIsNotNull() {
			addCriterion("action is not null");
			return (Criteria) this;
		}

		public Criteria andActionEqualTo(String value) {
			addCriterion("action =", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionNotEqualTo(String value) {
			addCriterion("action <>", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionGreaterThan(String value) {
			addCriterion("action >", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionGreaterThanOrEqualTo(String value) {
			addCriterion("action >=", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionLessThan(String value) {
			addCriterion("action <", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionLessThanOrEqualTo(String value) {
			addCriterion("action <=", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionLike(String value) {
			addCriterion("action like", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionNotLike(String value) {
			addCriterion("action not like", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionIn(List<String> values) {
			addCriterion("action in", values, "action");
			return (Criteria) this;
		}

		public Criteria andActionNotIn(List<String> values) {
			addCriterion("action not in", values, "action");
			return (Criteria) this;
		}

		public Criteria andActionBetween(String value1, String value2) {
			addCriterion("action between", value1, value2, "action");
			return (Criteria) this;
		}

		public Criteria andActionNotBetween(String value1, String value2) {
			addCriterion("action not between", value1, value2, "action");
			return (Criteria) this;
		}

		public Criteria andLeafIsNull() {
			addCriterion("leaf is null");
			return (Criteria) this;
		}

		public Criteria andLeafIsNotNull() {
			addCriterion("leaf is not null");
			return (Criteria) this;
		}

		public Criteria andLeafEqualTo(Integer value) {
			addCriterion("leaf =", value, "leaf");
			return (Criteria) this;
		}

		public Criteria andLeafNotEqualTo(Integer value) {
			addCriterion("leaf <>", value, "leaf");
			return (Criteria) this;
		}

		public Criteria andLeafGreaterThan(Integer value) {
			addCriterion("leaf >", value, "leaf");
			return (Criteria) this;
		}

		public Criteria andLeafGreaterThanOrEqualTo(Integer value) {
			addCriterion("leaf >=", value, "leaf");
			return (Criteria) this;
		}

		public Criteria andLeafLessThan(Integer value) {
			addCriterion("leaf <", value, "leaf");
			return (Criteria) this;
		}

		public Criteria andLeafLessThanOrEqualTo(Integer value) {
			addCriterion("leaf <=", value, "leaf");
			return (Criteria) this;
		}

		public Criteria andLeafIn(List<Integer> values) {
			addCriterion("leaf in", values, "leaf");
			return (Criteria) this;
		}

		public Criteria andLeafNotIn(List<Integer> values) {
			addCriterion("leaf not in", values, "leaf");
			return (Criteria) this;
		}

		public Criteria andLeafBetween(Integer value1, Integer value2) {
			addCriterion("leaf between", value1, value2, "leaf");
			return (Criteria) this;
		}

		public Criteria andLeafNotBetween(Integer value1, Integer value2) {
			addCriterion("leaf not between", value1, value2, "leaf");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sys_menu
	 * @mbggenerated  Mon Dec 04 02:57:11 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_menu
     *
     * @mbggenerated do_not_delete_during_merge Mon Dec 04 00:42:04 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}