package com.gs.sys.mapper;

import com.gs.sys.model.SysCust;
import com.gs.sys.model.SysCustExample;
import com.gs.common.PaginationExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SysCustMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_cust
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	int countByExample(SysCustExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_cust
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	int deleteByExample(SysCustExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_cust
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	int deleteByPrimaryKey(Long custId);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_cust
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	int insert(SysCust record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_cust
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	int insertSelective(SysCust record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_cust
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	List<SysCust> selectByExample(SysCustExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_cust
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	SysCust selectByPrimaryKey(Long custId);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_cust
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	int updateByExampleSelective(@Param("record") SysCust record,
			@Param("example") SysCustExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_cust
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	int updateByExample(@Param("record") SysCust record,
			@Param("example") SysCustExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_cust
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	int updateByPrimaryKeySelective(SysCust record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_cust
	 * @mbggenerated  Sun Dec 03 22:02:58 CST 2017
	 */
	int updateByPrimaryKey(SysCust record);
	long countByPageExample(PaginationExample example);
    List<SysCust> selectByPageExample(PaginationExample example);
}