package com.gs.sys.mapper;

import com.gs.sys.model.SysUser;
import com.gs.sys.model.SysUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Sun Nov 26 17:47:50 CST 2017
	 */
	int countByExample(SysUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Sun Nov 26 17:47:50 CST 2017
	 */
	int deleteByExample(SysUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Sun Nov 26 17:47:50 CST 2017
	 */
	int deleteByPrimaryKey(Long userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Sun Nov 26 17:47:50 CST 2017
	 */
	int insert(SysUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Sun Nov 26 17:47:50 CST 2017
	 */
	int insertSelective(SysUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Sun Nov 26 17:47:50 CST 2017
	 */
	List<SysUser> selectByExample(SysUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Sun Nov 26 17:47:50 CST 2017
	 */
	SysUser selectByPrimaryKey(Long userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Sun Nov 26 17:47:50 CST 2017
	 */
	int updateByExampleSelective(@Param("record") SysUser record,
			@Param("example") SysUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Sun Nov 26 17:47:50 CST 2017
	 */
	int updateByExample(@Param("record") SysUser record,
			@Param("example") SysUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Sun Nov 26 17:47:50 CST 2017
	 */
	int updateByPrimaryKeySelective(SysUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Sun Nov 26 17:47:50 CST 2017
	 */
	int updateByPrimaryKey(SysUser record);
}